In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# 一、tf.constant（常量声明）

# 1.数值类型
data = tf.constant([1,2])
print(data)

# 2.字符串类型
data = tf.constant('hello')
print(data)

# 3.布尔类型
#TensorFlow 的布尔类型和 Python 语言的布尔类型并不等价，不能通用
data1 = tf.constant(True)
data2 = True
print(data1 == data2)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(b'hello', shape=(), dtype=string)
False


In [3]:
# 二、tf.Variable（变量声明）
a1 = 7
a2 = tf.Variable(a1)
a3 = tf.Variable([[0,1,2],[2,2,2]])

print(a1)
print(a2)
print(a3)

7
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [2, 2, 2]])>


In [4]:
# 三、tf.bitcast或tf.cast（改变数据类型）
a = tf.constant(32.0)
b = tf.bitcast(a,type=tf.int32)
c = tf.cast(b,tf.float64)
print(a)
print(b)
print(c)

tf.Tensor(32.0, shape=(), dtype=float32)
tf.Tensor(1107296256, shape=(), dtype=int32)
tf.Tensor(1107296256.0, shape=(), dtype=float64)


In [5]:
# 四、创建张量

# 1.从列表创建张量
print(tf.convert_to_tensor([1,2.,3]))
print()

# 2.从数组中创建张量
print(tf.convert_to_tensor(np.array([[1,2.],[3,4]])))
print()

# 3.创建全0和全1的向量
print(tf.zeros([2]))
print(tf.ones([4]))
print()

# 4.创建全0和全1的矩阵
print(tf.zeros([2,4]))
print(tf.ones([3,2]))
print()

# 5.创建与张量a形状一样的全0张量：
a = tf.ones([2,3]) # 创建一个矩阵
print(tf.zeros_like(a)) # 创建一个与a形状相同，但是全0的新矩阵
print()

# 6.创建与张量a形状一样的全1张量：
a = tf.zeros([2,3]) # 创建一个矩阵
print(tf.ones_like(a)) # 创建一个与a形状相同，但是全1的新矩阵
print()

# 7.创建自定义数值张量
print(tf.fill([2,2], 99)) #创建所有元素为99的矩阵
print()

# 8.创建已知分布的张量

#8.1tf.random.normal（随机生成符合正态分布的Tensor）
a = tf.random.normal(shape=[2,3],mean=2)
print(a)
print()
print(a.numpy())
print()

#shape: 输出张量的形状，必选
#mean: 正态分布的中心值即均值，默认为0
#stddev: 正态分布的标准差，默认为1.0
#dtype: 输出的类型，默认为tf.float32
#seed: 随机数种子，是一个整数，当设置之后，每次生成的随机数都一样
#name: 操作的名称

#8.2tf.random.uniform（随机生成符合均匀分布的Tensor）
a = tf.random.uniform(shape=[2,3],minval=1,maxval=10,seed=8,dtype=tf.int32)
print(a)
print()
print(a.numpy())
print()

# 9.创建序列
print( tf.range(1,10,2))

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)

tf.Tensor([0. 0.], shape=(2,), dtype=float32)
tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[99 99]
 [99 99]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[2.0050347  2.1918166  2.1967683 ]
 [0.70630705 1.6620154  0.65952814]], shape=(2, 3), dtype=float32)

[[2.0050347  2.1918166  2.1967683 ]
 [0.70630705 1.6620154  0.65952814]]

tf.Tensor(
[[4 9 9]
 [6 4 9]], shape=(2, 3), dtype=int32)

[[4 9 9]
 [6 4 9]]

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [6]:
# 五、索引与切片

# 1.索引
x = tf.random.normal([4,6,6,3]) # 创建4D张量

#取第1张图片的数据
print(x[0])
print()

#取第1张图片的第2行
print(x[0][1])
print()

#取第1张图片的第2行第3列的数据
print(x[0][1][2])
print()

#取第3张图片的第2行第1列的像素，B通道(第 2 个通道)颜色强度值
print(x[2][1][0][1])
print()

#当张量的维度数较高时，使用[𝑖][𝑗]. . .[𝑘]的方式书写不方便，可以采用[𝑖,𝑗, … , 𝑘]的方式索引，它们是等价的。
#取第2张图片，第2行，第3列的数据
print(x[1,1,2])

tf.Tensor(
[[[ 0.50824964  0.4737508   0.6022392 ]
  [-0.678725   -0.90917534 -1.8929946 ]
  [-1.4360739   0.81102586  0.30779988]
  [-0.7692204   0.30043572 -0.6317594 ]
  [-0.88931555  0.771565   -0.3906411 ]
  [-0.6804628  -1.3308413  -1.0551364 ]]

 [[ 0.8247307  -0.16783491 -2.3252935 ]
  [-0.6526264   1.4084926   1.9640408 ]
  [-0.5482488   0.76925004  0.80716306]
  [-0.17672431 -1.7673584   0.36537415]
  [-0.9724369  -0.19882043  0.6102701 ]
  [-0.18393852  0.15106149  0.61718565]]

 [[ 0.8160369   2.761211   -0.1814909 ]
  [-2.1020546  -0.07593818  0.4414888 ]
  [ 1.1253241  -0.92563915  0.5294218 ]
  [-0.6427986   0.01776238 -0.75979   ]
  [ 2.2722716  -1.0058442  -0.9081826 ]
  [-0.66184783 -1.9628239   1.7014719 ]]

 [[-0.38072243  0.08528593  1.7451619 ]
  [-1.7675713  -0.25099733 -0.27552947]
  [-1.3305908  -0.48720887 -0.36716932]
  [-0.12220445 -0.17022449  0.0374745 ]
  [ 0.22845414  1.6699435  -0.3000444 ]
  [-0.31990975 -1.538705   -0.2709172 ]]

 [[-0.18877211 -0.120

In [7]:
# 2.切片(start: end: step)

#读取所有图片、隔行采样、隔列采样、读取所有通道数据
print( x[:,0:28:2,0:28:2,:])
print()

#行、列逆序间隔采样
print(x[0,::-2,::-2])
print()

'''
为了避免出现像 [: , : , : ,1]这样过多冒号的情况，可以使用⋯符号表示取多个维度上所
有的数据
'''
#读取最后2张图片
print(x[2:,...]) #高、宽、通道维度全部采集，等价于 x[2:]

tf.Tensor(
[[[[ 0.50824964  0.4737508   0.6022392 ]
   [-1.4360739   0.81102586  0.30779988]
   [-0.88931555  0.771565   -0.3906411 ]]

  [[ 0.8160369   2.761211   -0.1814909 ]
   [ 1.1253241  -0.92563915  0.5294218 ]
   [ 2.2722716  -1.0058442  -0.9081826 ]]

  [[-0.18877211 -0.12094232  0.24271683]
   [-1.4567888  -1.9847263  -1.3680512 ]
   [-1.0790803  -0.10332607 -2.0564082 ]]]


 [[[ 1.1095245  -1.5639743  -0.20459451]
   [-0.8621914   0.02169924 -0.11253659]
   [-0.8262552  -1.7213181   1.261009  ]]

  [[ 0.28984308 -0.9332081  -1.5628093 ]
   [-0.4239513   0.9956673  -0.19403884]
   [-0.1388223   0.70321035 -1.4528259 ]]

  [[-1.5224465   0.06760433 -0.7223576 ]
   [-1.1672586  -0.89635473  0.04568629]
   [-0.32735783 -1.4414088  -0.03732293]]]


 [[[-0.849695    0.05781463  0.07267959]
   [ 1.3500048  -1.9250383  -0.3748379 ]
   [ 0.8395184  -0.35256997  1.4800836 ]]

  [[-1.4451728  -0.7591141  -0.46388584]
   [ 1.366898   -0.2089776  -0.07395955]
   [-0.5237021   0.5719624  

In [8]:
# 六、维度变换
#1.tf.reshape （多阶Tensor形态变化）
b1 = tf.Variable([[0,1,2],[4,5,6]])
print(b1)

b2 = tf.reshape(b1,[3,2])
print(b2)
print()

#2.tf.expand_dims（增加维度）
a = tf.constant([[1],[2],[3]])
print(a)

b = tf.expand_dims(a,0) #0是添加维度的下标，即最外层添加一个维度
print(b)
print()

#3.tf.squeeze（删除维度）
c = tf.squeeze(b,0)
print(c)
print()

#4.tf.transpose（交换维度）
x = tf.constant([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                 [10, 11, 12]]])
print(x)
a = tf.transpose(x,perm=[0,2,1]) #0–代表的是最外层的一维, 1–代表外向内数第二维, 2–代表最内层的一维
print(a) #2*2*3变为2*3*2
print()
print(a.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [4, 5, 6]])>
tf.Tensor(
[[0 1]
 [2 4]
 [5 6]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]], shape=(2, 3, 2), dtype=int32)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [9]:
# 七、复制数据

# 1.tf.tile(x, multiples)
#，multiples 分别指定了每个维度上面的复制倍数，对应位置为 1 表明不复制，为 2 表明新长度为原来长度的2 倍
b = tf.constant([1,2]) #创建向量b
b = tf.expand_dims(b, axis=0) # 插入新维度，变成矩阵
print(b)
b = tf.tile(b, multiples=[2,1])
print(b)
print()

# 2.Broadcasting(广播机制)
a = tf.random.normal([2,4,3])
b = tf.random.normal([4,3])
print('a')
print(a)
print('b')
print(b)
print('a+b') #操作符+在遇到shape不一致的 2 个张量时，会自动考虑将2个张量自动扩展到一致的shape，然后再调用tf.add完成张量相加运算
print(a+b)

tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [1 2]], shape=(2, 2), dtype=int32)

a
tf.Tensor(
[[[-1.7365359  -0.579554    0.90367764]
  [-0.08709873  1.3670171   0.33483225]
  [ 1.1239908  -2.5393217  -0.73685807]
  [ 0.6100827  -0.40933266 -1.8553503 ]]

 [[-0.9365184   1.8084974   0.54663575]
  [ 0.47172767 -2.0992267   2.005945  ]
  [ 0.01743619 -0.5021706   0.7816504 ]
  [ 0.42757702  0.6989862   0.30794623]]], shape=(2, 4, 3), dtype=float32)
b
tf.Tensor(
[[-1.7400575  -0.37973708  0.93470067]
 [-0.41487893 -0.8283052  -0.5473837 ]
 [ 1.0384055   1.5220569   0.4423968 ]
 [-2.4395819  -0.5547633   0.43775272]], shape=(4, 3), dtype=float32)
a+b
tf.Tensor(
[[[-3.4765935  -0.9592911   1.8383783 ]
  [-0.5019777   0.53871197 -0.21255147]
  [ 2.1623964  -1.0172647  -0.29446128]
  [-1.8294992  -0.96409595 -1.4175975 ]]

 [[-2.676576    1.4287603   1.4813364 ]
  [ 0.05684873 -2.927532    1.4585612 ]
  [ 1.0558417   1.0198863   1.2240472 ]
  [-2.0120049   0.14422286  0.74

In [10]:
# 八、数学运算

# 1.加、减、乘、除运算
a = tf.range(5)
b = tf.constant(2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b) # 整除运算
print(a%b) # 余除运算
print()

# 2.乘方运算
x = tf.range(4)
print(x)
print(tf.pow(x,3)) # 乘方运算
print(x**2) #乘方运算符
x = tf.cast(x, dtype=tf.float32)
x = tf.square(x)
print(x) #平方
print(tf.sqrt(x)) #平方根

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([-2 -1  0  1  2], shape=(5,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([0.  0.5 1.  1.5 2. ], shape=(5,), dtype=float64)
tf.Tensor([0 0 1 1 2], shape=(5,), dtype=int32)
tf.Tensor([0 1 0 1 0], shape=(5,), dtype=int32)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([ 0  1  8 27], shape=(4,), dtype=int32)
tf.Tensor([0 1 4 9], shape=(4,), dtype=int32)
tf.Tensor([0. 1. 4. 9.], shape=(4,), dtype=float32)
tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float32)
