In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# 一、合并

# 1.拼接
a1 = tf.constant([[0,1,2],[2,3,2]])
a2 = tf.constant([[0,1,2],[4,5,6]])
b1 = tf.concat([a1,a2],axis=1)
b2 = tf.concat([a1,a2],axis=0)
print(a1)
print(a2)
print(b1)
print(b2)
print()
a = tf.random.normal([4,22,1]) # 模拟成绩册 A
b = tf.random.normal([4,22,8]) # 模拟成绩册 B
print(a.shape)
print(b.shape)
c = tf.concat([a,b],axis=2) # 拼接合并成绩册
print(c.shape)
print()

# 2.堆叠
a = tf.random.normal([35,8,9])
b = tf.random.normal([35,8,9])
c1 = tf.stack([a,b],axis=0)
c2 = tf.stack([a,b],axis=-1)
c3 = tf.stack([a,b],axis=1)
print(c1.shape)
print(c2.shape)
print(c3.shape)

tf.Tensor(
[[0 1 2]
 [2 3 2]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 1 2]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 1 2 0 1 2]
 [2 3 2 4 5 6]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[0 1 2]
 [2 3 2]
 [0 1 2]
 [4 5 6]], shape=(4, 3), dtype=int32)

(4, 22, 1)
(4, 22, 8)
(4, 22, 9)

(2, 35, 8, 9)
(35, 8, 9, 2)
(35, 2, 8, 9)


In [3]:
# 二、分割

# 1.等长切割为10份
x = tf.random.normal([10,35,8])
result = tf.split(x, num_or_size_splits=10, axis=0)
print(len(result)) #返回的列表为10个张量的列表
print(result[0].shape)
print()

# 2.任意分割为4份
x = tf.random.normal([10,35,8])
result = tf.split(x, num_or_size_splits=[1,2,3,2], axis=2)
print(len(result)) #返回的列表为10个张量的列表
print(result[2].shape)

10
(1, 35, 8)

4
(10, 35, 3)


In [4]:
# 三、数据统计

# 1.向量范数
x = tf.ones([2,2])
print(tf.norm(x,ord=1)) #计算L1范数
print(tf.norm(x,ord=2) )#计算L2范数
print(tf.norm(x,ord=np.inf)) #计算∞-范数
print()

# 2.最值、均值、和
x = tf.random.normal([4,3])
print(x)
print(tf.reduce_max(x,axis=0))
print(tf.reduce_min(x,axis=1))
print(tf.reduce_max(x,axis=0))
print(tf.reduce_sum(x,axis=-1))
print(tf.reduce_max(x))

tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)

tf.Tensor(
[[-1.2268146  -1.0487142  -0.0996369 ]
 [-0.6973206   0.20476392  0.03961945]
 [-0.23555212 -1.9146347   2.0657573 ]
 [-0.66752005  0.38381675 -0.64654887]], shape=(4, 3), dtype=float32)
tf.Tensor([-0.23555212  0.38381675  2.0657573 ], shape=(3,), dtype=float32)
tf.Tensor([-1.2268146  -0.6973206  -1.9146347  -0.66752005], shape=(4,), dtype=float32)
tf.Tensor([-0.23555212  0.38381675  2.0657573 ], shape=(3,), dtype=float32)
tf.Tensor([-2.3751657  -0.45293722 -0.0844295  -0.9302522 ], shape=(4,), dtype=float32)
tf.Tensor(2.0657573, shape=(), dtype=float32)


In [5]:
# 四、张量比较
# 1.比较相同元素
a = tf.constant([1,3,5,7,9])
b = tf.constant([1,2,4,6,8])
out = tf.equal(a,b)
print(out)
print()

# 2.tf.math.argmax（返回数组内最大值的索引）
a = tf.constant([[7,12,2,4],
                [3,1,7,8],
                [11,15,2,5]])
x = tf.argmax(a,axis=1)
print(x)
print()
print(x.numpy())

tf.Tensor([ True False False False False], shape=(5,), dtype=bool)

tf.Tensor([1 3 1], shape=(3,), dtype=int64)

[1 3 1]


In [6]:
# 五、填充与复制
# 1.填充
a = tf.constant([1,2,3,4,5,6]) # 第一个句子
b = tf.constant([7,8,1,6]) # 第二个句子
b = tf.pad(b, [[0,2]]) # 句子末尾填充2个0
print(a)
print(b) # 填充后的结果
print(tf.stack([a,b],axis=0))
print()

# 2.复制
x = tf.random.normal([4,32,32,3])
print(x.shape)
print(tf.tile(x,[2,3,3,1]).shape)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor([7 8 1 6 0 0], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3 4 5 6]
 [7 8 1 6 0 0]], shape=(2, 6), dtype=int32)

(4, 32, 32, 3)
(8, 96, 96, 3)


In [7]:
# 六、数据限幅

# 1.上或下限幅
x = tf.range(9)
print(x)
print(tf.maximum(x,2)) # 下限幅到 2
print(tf.minimum(x,7)) # 上限幅到 7
print()
      
# 2.上下限幅
x = tf.range(12)
print(x)
print(tf.minimum(tf.maximum(x,2),7)) # 限幅为 2~7
#简便方法
print(tf.clip_by_value(x,2,7)) # 限幅为 2~7

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([2 2 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 7], shape=(9,), dtype=int32)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor([2 2 2 3 4 5 6 7 7 7 7 7], shape=(12,), dtype=int32)
tf.Tensor([2 2 2 3 4 5 6 7 7 7 7 7], shape=(12,), dtype=int32)
