In [12]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [13]:
# 一、tf.constant（常量声明）

data = tf.constant([1,2])
print(data)

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [17]:
# 二、tf.Variable（变量声明）
a1 = 7
a2 = tf.Variable(a1)
a3 = tf.Variable([[0,1,2],[2,2,2]])

print(a1)
print(a2)
print(a3)

7
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [2, 2, 2]])>


In [19]:
# 三、tf.reshape （多阶Tensor形态变化）
b1 = tf.Variable([[0,1,2],[4,5,6]])
print(b1)
print()

b2 = tf.reshape(b1,[3,2])
print(b2)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [4, 5, 6]])>

tf.Tensor(
[[0 1]
 [2 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [25]:
# 四、math.reduce_mean（Tensor求平均）
a = tf.constant([1,2.,3,4,5,6,7.])
print(a.dtype)
result1 = tf.math.reduce_mean(a)
print(result1)
print(tf.math.reduce_mean(a,keepdims=True)) #配置输出结果保证二维矩阵性
print()

b = tf.Variable([[0,1,2],[4,5,6]])
print(b)
print(b.dtype)
result2 = tf.math.reduce_mean(b) #默认为全行全列求平均值，可加axis指定行或者列计算平均值
print(result2) #结果本来为3.5，但数据类型为int所以强转为3
result3 = tf.math.reduce_mean(b,axis=1) #默认为全行全列求平均值，可加axis指定行或者列计算平均值
print(result3)
print()

<dtype: 'float32'>
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([4.], shape=(1,), dtype=float32)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [4, 5, 6]])>
<dtype: 'int32'>
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 5], shape=(2,), dtype=int32)



In [28]:
# 五、tf.random.normal（随机生成符合正态分布的Tensor）
a = tf.random.normal(shape=[2,3],mean=2)
print(a.numpy())

#shape: 输出张量的形状，必选
#mean: 正态分布的中心值即均值，默认为0
#stddev: 正态分布的标准差，默认为1.0
#dtype: 输出的类型，默认为tf.float32
#seed: 随机数种子，是一个整数，当设置之后，每次生成的随机数都一样
#name: 操作的名称

[[1.3627298 4.296895  2.216996 ]
 [4.1196985 2.1322417 1.7661102]]


In [30]:
# 六、tf.random.uniform（随机生成符合均匀分布的Tensor）
a = tf.random.uniform(shape=[2,3],minval=1,maxval=10,seed=8,dtype=tf.int32)
print(a)
print()
print(a.numpy())

tf.Tensor(
[[4 4 7]
 [2 2 8]], shape=(2, 3), dtype=int32)

[[4 4 7]
 [2 2 8]]


In [41]:
# 七、 tf.transpose（矩阵转置）
x = tf.constant([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                 [10, 11, 12]]])
print(x)
print()
a = tf.transpose(x,perm=[0,2,1]) #0–代表的是最外层的一维, 1–代表外向内数第二维, 2–代表最内层的一维
print(a) #2*2*3变为2*3*2
print()
print(a.numpy())

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)

tf.Tensor(
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]], shape=(2, 3, 2), dtype=int32)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [44]:
# 八、tf.math.argmax（返回数组内最大值的索引）
a = tf.constant([[7,12,2,4],
                [3,1,7,8],
                [11,15,2,5]])
x = tf.math.argmax(a,axis=1)
print(x)
print()
print(x.numpy())

tf.Tensor([1 3 1], shape=(3,), dtype=int64)

[1 3 1]


In [45]:
# 九、expand_dims（增加维度）
a = tf.constant([[1],[2],[3]])
print(a)
print()
b = tf.expand_dims(a,0) #0是添加维度的下标，即最外层添加一个维度
print(b)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)

tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)


In [50]:
# 十、tf.concat（Tensor拼接）
a1 = tf.constant([[0,1,2],[2,2,2]])
a2 = tf.constant([[0,1,2],[4,5,6]])
b = tf.concat([a1,a2],axis=1)
print(b)
print()
c = tf.concat([a1,a2],axis=0)
print(c)

tf.Tensor(
[[0 1 2 0 1 2]
 [2 2 2 4 5 6]], shape=(2, 6), dtype=int32)

tf.Tensor(
[[0 1 2]
 [2 2 2]
 [0 1 2]
 [4 5 6]], shape=(4, 3), dtype=int32)


In [51]:
# 十一、tf.bitcast（改变数据类型）
a = tf.constant(32.0)
b = tf.bitcast(a,type=tf.int32)
print(a)
print(b)

tf.Tensor(32.0, shape=(), dtype=float32)
tf.Tensor(1107296256, shape=(), dtype=int32)


In [55]:
# 十二、tf.keras高阶API

#构建神经网络模型
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(input_dim=1,units=1))
model.compile(loss='mse',optimizer='sgd')

In [56]:
#训练神经网络模型
X = np.linspace(-10,10,700)
Y = 2*X+100+np.random.normal(0,0.1,(700,))
model.fit(X,Y,verbose=1,epochs=200,validation_split=0.2)

Train on 560 samples, validate on 140 samples
Epoch 1/200
560/560 [==============================] - 0s 165us/sample - loss: 6528.7439 - val_loss: 16773.4602
Epoch 2/200
560/560 [==============================] - 0s 38us/sample - loss: 3508.5672 - val_loss: 8053.7094
Epoch 3/200
560/560 [==============================] - 0s 48us/sample - loss: 1922.9253 - val_loss: 4945.6240
Epoch 4/200
560/560 [==============================] - 0s 47us/sample - loss: 1044.8799 - val_loss: 2026.6877
Epoch 5/200
560/560 [==============================] - 0s 46us/sample - loss: 565.7691 - val_loss: 979.6439
Epoch 6/200
560/560 [==============================] - 0s 38us/sample - loss: 306.2399 - val_loss: 564.4175
Epoch 7/200
560/560 [==============================] - 0s 37us/sample - loss: 169.8513 - val_loss: 354.2992
Epoch 8/200
560/560 [==============================] - 0s 38us/sample - loss: 90.9551 - val_loss: 202.0912
Epoch 9/200
560/560 [==============================] - 0s 40us/sample - loss: 49.

560/560 [==============================] - 0s 38us/sample - loss: 0.0102 - val_loss: 0.0104
Epoch 79/200
560/560 [==============================] - 0s 35us/sample - loss: 0.0102 - val_loss: 0.0117
Epoch 80/200
560/560 [==============================] - 0s 40us/sample - loss: 0.0101 - val_loss: 0.0109
Epoch 81/200
560/560 [==============================] - 0s 33us/sample - loss: 0.0102 - val_loss: 0.0105
Epoch 82/200
560/560 [==============================] - 0s 42us/sample - loss: 0.0100 - val_loss: 0.0109
Epoch 83/200
560/560 [==============================] - 0s 36us/sample - loss: 0.0102 - val_loss: 0.0112
Epoch 84/200
560/560 [==============================] - 0s 32us/sample - loss: 0.0102 - val_loss: 0.0107
Epoch 85/200
560/560 [==============================] - 0s 33us/sample - loss: 0.0101 - val_loss: 0.0105
Epoch 86/200
560/560 [==============================] - 0s 31us/sample - loss: 0.0102 - val_loss: 0.0111
Epoch 87/200
560/560 [==============================] - 0s 33us/samp

560/560 [==============================] - 0s 35us/sample - loss: 0.0101 - val_loss: 0.0105
Epoch 156/200
560/560 [==============================] - 0s 37us/sample - loss: 0.0101 - val_loss: 0.0110
Epoch 157/200
560/560 [==============================] - 0s 34us/sample - loss: 0.0103 - val_loss: 0.0131
Epoch 158/200
560/560 [==============================] - 0s 33us/sample - loss: 0.0102 - val_loss: 0.0104
Epoch 159/200
560/560 [==============================] - 0s 33us/sample - loss: 0.0101 - val_loss: 0.0105
Epoch 160/200
560/560 [==============================] - 0s 33us/sample - loss: 0.0101 - val_loss: 0.0107
Epoch 161/200
560/560 [==============================] - 0s 33us/sample - loss: 0.0102 - val_loss: 0.0113
Epoch 162/200
560/560 [==============================] - 0s 32us/sample - loss: 0.0101 - val_loss: 0.0104
Epoch 163/200
560/560 [==============================] - 0s 38us/sample - loss: 0.0101 - val_loss: 0.0105
Epoch 164/200
560/560 [==============================] - 0s 

In [59]:
#保存神经网络模型
filename = 'line_model.h5' #h5格式保存
model.save(filename)

In [60]:
#加载模型进行运算
x = tf.constant([0.5])
model = tf.keras.models.load_mdodel(filename)
y = model.predict(x)
print(y)

[[101.003685]]
